### ISSUE TITLE
Unkomplizierterer Prüfungsverleih

### ISSUE THREAD

**Issue by colfes** [FIUS/Verleihsystem-TTF#82]
Für unkomplizierteren Verleih sollten einige Features in "Lendings" integriert werden. Ausleihen über Search / Items benötigt sehr viele Klicks pro Vorgang.

- Es sollten nur Prüfungsordner angezeigt werden (bzw. Objekte, die auch verleihbar sind).
- Ebenso Einführung von Kürzeln, analog zum Suchfunktion-Issue
- Wenn möglich, dynamische Anzeige der Prüfungsordner passend zur Eingabe im Suchfeld

**Comment by mee4895** [comment]
Mostly irrelevant because,
  - lendings is for admins to see current lendings not to create them
  - to lend a Item via Search or Items (assuming you found it already) takes 3 klicks and one Input field in most cases which is not 'sehr viele'
  -  duplication of Issue#81
  - the dynamic search is currently not sensible

Rest was moved to: Issue#93
